version: "3"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        environment: 
            DATABASE_URL: postgres://docker:docker@postgres:5432/blog
            NODE_ENV: development
            PORT: 3000
        ports:
            - "8080:3000"

    postgres:
        image: postgres:10.4
        ports:
            - "35000:5432"
        environment: 
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: blog