version: "3"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        environment: 
            DATABASE_URL: postgres://docker:docker@localhost:5432/blog
            NODE_ENV: development
            PORT: 4000
        ports:
            - "4000:4000"

    postgres:
        image: postgres:10.4
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: blog